package kr.kyg.ijplugin.egovframe.render

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import kr.kyg.ijplugin.egovframe.assets.ConfigTemplate
import kr.kyg.ijplugin.egovframe.assets.TemplateCatalog
import kr.kyg.ijplugin.egovframe.config.ConfigGenerator
import org.junit.jupiter.api.Assertions.fail
import org.junit.jupiter.api.Test
import java.math.BigDecimal

/** Byte-for-byte parity gate for fixtures generated by tools/golden-gen. */
class GoldenRenderTest {

  @Test
  fun rendersEveryGoldenFixture() {
    val index = resource("golden/index.json") ?: throw AssertionError("Missing required golden/index.json fixture gate")
    val root = JsonParser.parseString(index).asJsonObject
    renderCrud(root.array("crud"))
    renderConfig(root.array("config"))
  }

  private fun renderCrud(cases: Iterable<JsonElement>) {
    cases.forEach { element ->
      val case = element.asJsonObject
      val caseName = case.string("case")
      val context =
        jsonValue(JsonParser.parseString(resourceRequired(case.string("context")))) as MutableMap<String, Any?>
      val outputs = case.obj("outputs")

      outputs.entrySet().forEach { (templateName, goldenPath) ->
        val actual = EgovHandlebars.render(
          resourceRequired("egovframe/code/$templateName"),
          LinkedHashMap(context),
        )
        assertGolden("crud/$caseName/$templateName", resourceRequired(goldenPath.asString), actual)
      }
    }
  }

  private fun renderConfig(cases: Iterable<JsonElement>) {
    cases.forEach { element ->
      val case = element.asJsonObject
      val slug = case.string("slug")
      val displayName = case.string("displayName")
      val formData = jsonValue(JsonParser.parseString(resourceRequired(case.string("formData")))) as Map<String, Any?>
      val outputs = case.obj("outputs")
      val variantOverrides = case.obj("variantOverrides")

      val configTemplate = resolveConfigTemplate(displayName)

      outputs.entrySet().forEach { (variant, goldenPath) ->
        val variantFormData = LinkedHashMap(formData)
        val overrides = jsonValue(variantOverrides.getAsJsonObject(variant)) as Map<String, Any?>
        variantFormData.putAll(overrides)

        val generationType = resolveGenerationType(variant)
        val prepared = ConfigGenerator.prepare(
          template = configTemplate,
          generationType = generationType,
          formData = variantFormData,
          defaultPackageName = DEFAULT_PACKAGE_NAME,
        )
        val actual = prepared.render()
        assertGolden("config/$slug/$variant", resourceRequired(goldenPath.asString), actual)
      }
    }
  }

  private fun resolveConfigTemplate(displayName: String): ConfigTemplate =
    TemplateCatalog.configs.first { it.displayName == displayName }

  private fun resolveGenerationType(variant: String): ConfigGenerator.GenerationType = when (variant) {
    "xml" -> ConfigGenerator.GenerationType.XML
    "java" -> ConfigGenerator.GenerationType.JAVA
    "yaml" -> ConfigGenerator.GenerationType.YAML
    "properties" -> ConfigGenerator.GenerationType.PROPERTIES
    else -> throw AssertionError("Unknown variant: $variant")
  }

  /** Gson's usual Map adapter converts all numbers to Double; retain integers. */
  private fun jsonValue(element: JsonElement): Any? = when {
    element.isJsonNull -> null
    element.isJsonArray -> element.asJsonArray.map(::jsonValue)
    element.isJsonObject -> LinkedHashMap<String, Any?>().also { map ->
      element.asJsonObject.entrySet().forEach { (name, value) -> map[name] = jsonValue(value) }
    }

    else -> element.asJsonPrimitive.let { primitive ->
      when {
        primitive.isBoolean -> primitive.asBoolean
        primitive.isNumber -> parseNumber(primitive.asString)
        else -> primitive.asString
      }
    }
  }

  private fun parseNumber(raw: String): Number {
    val decimal = BigDecimal(raw)
    return if (decimal.scale() <= 0) {
      try {
        decimal.intValueExact()
      } catch (_: ArithmeticException) {
        decimal.longValueExact()
      }
    } else {
      decimal.toDouble()
    }
  }

  private fun assertGolden(name: String, expected: String, actual: String) {
    if (expected == actual) return
    val commonLength = minOf(expected.length, actual.length)
    val position = (0 until commonLength).firstOrNull { expected[it] != actual[it] } ?: commonLength
    fail<Unit>(
      "$name differs at character $position: expected ${snippet(expected, position)}, " +
        "actual ${snippet(actual, position)}",
    )
  }

  private fun snippet(value: String, at: Int): String {
    val start = (at - 20).coerceAtLeast(0)
    val end = (at + 20).coerceAtMost(value.length)
    return value.substring(start, end).replace("\n", "\\n").replace("\r", "\\r").quoted()
  }

  private fun resource(path: String): String? = javaClass.classLoader.getResourceAsStream(path)
    ?.bufferedReader(Charsets.UTF_8)
    ?.use { it.readText() }

  private fun resourceRequired(path: String): String =
    resource(path) ?: throw AssertionError("Missing required resource: $path")

  private fun JsonObject.array(name: String) = getAsJsonArray(name)
  private fun JsonObject.obj(name: String) = getAsJsonObject(name)
  private fun JsonObject.string(name: String) = get(name).asString

  private fun String.quoted() = "\"$this\""

  private companion object {
    const val DEFAULT_PACKAGE_NAME = "egovframework.example.sample"
  }
}
